// Copyright 2026 Noah Qin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

import Foundation

/// Per-session startup wrappers source the user's files, then the bundled hooks.
/// No edits to ~/.zshrc. ZDOTDIR is restored before the user's .zshrc runs.
enum ZshBootstrap {
    private static var folders: [URL] = []
    static func removeGeneratedFiles() {
        for folder in folders { try? FileManager.default.removeItem(at: folder) }
        folders.removeAll()
    }
    static func environment(_ original: [String: String], executable: String, arguments: [String]) -> [String: String] {
        guard (executable as NSString).lastPathComponent == "zsh",
            arguments == ["-l"] || arguments.isEmpty else { return original }
        let fm = FileManager.default
        let folder = fm.temporaryDirectory.appendingPathComponent("corta-zsh-\(UUID().uuidString)")
        let userDirectory = original["ZDOTDIR"] ?? original["HOME"] ?? NSHomeDirectory()
        // Quotes are generated by the application, not by a terminal report.
        func quote(_ value: String) -> String { "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'" }
        do {
            try fm.createDirectory(at: folder, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
            let hook = folder.appendingPathComponent("corta.zsh")
            try ShellIntegrationScript.script(for: .zsh).write(to: hook, atomically: true, encoding: .utf8)
            let restore = "if [[ $CORTA_USER_ZDOTDIR_SET == 1 ]]; then ZDOTDIR=$CORTA_USER_ZDOTDIR; else unset ZDOTDIR; fi\n"
            let capture = "export CORTA_USER_ZDOTDIR=${ZDOTDIR:-$HOME}\nexport CORTA_USER_ZDOTDIR_SET=${+ZDOTDIR}\n"
            for file in [".zshenv", ".zprofile"] {
                let script = restore + "[[ -r ${ZDOTDIR:-$HOME}/\(file) ]] && source ${ZDOTDIR:-$HOME}/\(file)\n" + capture + "ZDOTDIR=\(quote(folder.path))\n"
                try script.write(to: folder.appendingPathComponent(file), atomically: true, encoding: .utf8)
            }
            let rc = restore + "unset CORTA_USER_ZDOTDIR CORTA_USER_ZDOTDIR_SET\n[[ -r ${ZDOTDIR:-$HOME}/.zshrc ]] && source ${ZDOTDIR:-$HOME}/.zshrc\nsource \(quote(hook.path))\n"
            try rc.write(to: folder.appendingPathComponent(".zshrc"), atomically: true, encoding: .utf8)
            folders.append(folder)
            var env = original
            env["CORTA_USER_ZDOTDIR"] = userDirectory
            env["CORTA_USER_ZDOTDIR_SET"] = original["ZDOTDIR"] == nil ? "0" : "1"
            env["ZDOTDIR"] = folder.path
            return env
        } catch {
            try? fm.removeItem(at: folder)
            return original
        }
    }
}
